package com.smartgym.manager.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CheckInAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInAllPropertiesEquals(CheckIn expected, CheckIn actual) {
        assertCheckInAutoGeneratedPropertiesEquals(expected, actual);
        assertCheckInAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInAllUpdatablePropertiesEquals(CheckIn expected, CheckIn actual) {
        assertCheckInUpdatableFieldsEquals(expected, actual);
        assertCheckInUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInAutoGeneratedPropertiesEquals(CheckIn expected, CheckIn actual) {
        assertThat(actual)
            .as("Verify CheckIn auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInUpdatableFieldsEquals(CheckIn expected, CheckIn actual) {
        assertThat(actual)
            .as("Verify CheckIn relevant properties")
            .satisfies(a -> assertThat(a.getCheckInTime()).as("check checkInTime").isEqualTo(expected.getCheckInTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckInUpdatableRelationshipsEquals(CheckIn expected, CheckIn actual) {
        assertThat(actual)
            .as("Verify CheckIn relationships")
            .satisfies(a -> assertThat(a.getMember()).as("check member").isEqualTo(expected.getMember()));
    }
}
