package com.smartgym.manager.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CoachAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoachAllPropertiesEquals(Coach expected, Coach actual) {
        assertCoachAutoGeneratedPropertiesEquals(expected, actual);
        assertCoachAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoachAllUpdatablePropertiesEquals(Coach expected, Coach actual) {
        assertCoachUpdatableFieldsEquals(expected, actual);
        assertCoachUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoachAutoGeneratedPropertiesEquals(Coach expected, Coach actual) {
        assertThat(actual)
            .as("Verify Coach auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoachUpdatableFieldsEquals(Coach expected, Coach actual) {
        assertThat(actual)
            .as("Verify Coach relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSpecialty()).as("check specialty").isEqualTo(expected.getSpecialty()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoachUpdatableRelationshipsEquals(Coach expected, Coach actual) {
        // empty method
    }
}
