package com.smartgym.manager.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MembershipAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipAllPropertiesEquals(Membership expected, Membership actual) {
        assertMembershipAutoGeneratedPropertiesEquals(expected, actual);
        assertMembershipAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipAllUpdatablePropertiesEquals(Membership expected, Membership actual) {
        assertMembershipUpdatableFieldsEquals(expected, actual);
        assertMembershipUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipAutoGeneratedPropertiesEquals(Membership expected, Membership actual) {
        assertThat(actual)
            .as("Verify Membership auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipUpdatableFieldsEquals(Membership expected, Membership actual) {
        assertThat(actual)
            .as("Verify Membership relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipUpdatableRelationshipsEquals(Membership expected, Membership actual) {
        assertThat(actual)
            .as("Verify Membership relationships")
            .satisfies(a -> assertThat(a.getMember()).as("check member").isEqualTo(expected.getMember()));
    }
}
